import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderWrapper from "@/components/HeaderWrapper";
import FooterWrapper from "@/components/FooterWrapper";
import ConditionalProviders from "@/components/ConditionalProviders";

// Force cache bust - latest version deployed
console.log('Cache bust - latest version deployed at:', new Date().toISOString());

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConditionalProviders>
          <HeaderWrapper />
          {children}
          <FooterWrapper />
        </ConditionalProviders>
      </body>
    </html>
  );
}
// Cache bust Tue Sep  9 12:01:21 IST 2025
