import "./globals.css";
import HeaderWrapper from "@/components/HeaderWrapper";
import FooterWrapper from "@/components/FooterWrapper";
import ConditionalProviders from "@/components/ConditionalProviders";
import ConditionalPadding from "@/components/ConditionalPadding";

// Force cache bust - latest version deployed
console.log('Cache bust - latest version deployed at:', new Date().toISOString());

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <ConditionalProviders>
          <HeaderWrapper />
          <ConditionalPadding>
            {children}
          </ConditionalPadding>
          <FooterWrapper />
        </ConditionalProviders>
      </body>
    </html>
  );
}
// Cache bust Tue Sep  9 12:01:21 IST 2025
